-- CreateTable
CREATE TABLE `Device` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `type` ENUM('machine', 'drone') NOT NULL,
    `status` ENUM('active', 'maintenance', 'inactive') NOT NULL,
    `dimension` VARCHAR(191) NULL,
    `weight` VARCHAR(191) NULL,
    `power` VARCHAR(191) NULL,
    `powerUsage` VARCHAR(191) NULL,
    `maxSpeed` VARCHAR(191) NULL,
    `workWidth` VARCHAR(191) NULL,
    `resolution` VARCHAR(191) NULL,
    `materialSupport` VARCHAR(191) NULL,
    `autoFeed` BOOLEAN NULL,
    `contourCut` BOOLEAN NULL,
    `digitalPanel` BOOLEAN NULL,
    `safetySensor` BOOLEAN NULL,
    `foldedDimension` VARCHAR(191) NULL,
    `flightTime` VARCHAR(191) NULL,
    `cameraSensor` VARCHAR(191) NULL,
    `videoResolution` VARCHAR(191) NULL,
    `gimbalRange` VARCHAR(191) NULL,
    `zoom` VARCHAR(191) NULL,
    `rtkModule` BOOLEAN NULL,
    `thermalCamera` VARCHAR(191) NULL,
    `obstacleSensing` VARCHAR(191) NULL,
    `ipRating` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Device_slug_key`(`slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
